import { ProductType } from "../../type/type";

export const dataProducts: ProductType[] = [
  {
    id: 1,
    title: "ПШЕНИЦЯ",
    price: 150,
    img: "wheat.webp",
  },
  {
    id: 2,
    title: "ЯЧМІНЬ",
    price: 50,
    img: "barley.webp",
  },
  {
    id: 3,
    title: "ОВЕС",
    price: 30,
    img: "oat.webp",
  },
  {
    id: 4,
    title: "КУКУРУДЗА",
    price: 220,
    img: "corn.webp",
  },
  {
    id: 5,
    title: "ПРОСО ЧЕРВОНЕ",
    price: 50,
    img: "milletRed.webp",
  },
  {
    id: 6,
    title: "ПРОСО ЖОВТЕ",
    price: 40,
    img: "milletYellow.webp",
  },
  {
    id: 7,
    title: "ПРОСО ЧОРНЕ",
    price: 150,
    img: "milletBlack.webp",
  },
  {
    id: 8,
    title: "СОРГО ЧЕРВОНЕ",
    price: 120,
    img: "sorghumRed.webp",
  },
  {
    id: 9,
    title: "КОРІАНДР",
    price: 550,
    img: "coriander.webp",
  },
  {
    id: 10,
    title: "КАНАРКОВА ТРАВА",
    price: 750,
    img: "canary.webp",
  },
  {
    id: 11,
    title: "ГРЕЧИХА",
    price: 150,
    img: "buckwheat.webp",
  },
  {
    id: 12,
    title: "СПЕЛЬТА",
    price: 350,
    img: "spelled.webp",
  },
  {
    id: 13,
    title: "ЛЬОН КОРИЧНЕВИЙ",
    price: 450,
    img: "linenBrown.webp",
  },
  {
    id: 14,
    title: "ЛЬОН ЗОЛОТИСТИ",
    price: 380,
    img: "linenGold.webp",
  },
  {
    id: 15,
    title: "СОНЯШНИК ОЛІЙНИЙ",
    price: 80,
    img: "sunflower.webp",
  },
  {
    id: 16,
    title: "СОНЯШНИК КОНДИТЕРСЬКИЙ",
    price: 40,
    img: "confectionerySunflower.webp",
  },
  {
    id: 17,
    title: "ГІРЧИЦЯ БІЛА",
    price: 98,
    img: "mustardWhite.webp",
  },
  {
    id: 18,
    title: "ГІРЧИЦЯ ЖОВТА",
    price: 88,
    img: "mustardYellow.webp",
  },
  {
    id: 19,
    title: "ГІРЧИЦЯ ЧОРНА",
    price: 188,
    img: "mustardBlack.webp",
  },
  {
    id: 20,
    title: "РІПАК",
    price: 228,
    img: "rapeseed.webp",
  },
  {
    id: 21,
    title: "СОЯ",
    price: 28,
    img: "soy.webp",
  },
  {
    id: 22,
    title: "СОЧЕВИЦЯ ЗЕЛЕНА",
    price: 128,
    img: "lentilGreen.webp",
  },
  {
    id: 23,
    title: "СОЧЕВИЦЯ ЧЕРВОНА",
    price: 208,
    img: "lentilRed.webp",
  },
  {
    id: 24,
    title: "ГОРОХ ЗЕЛЕНИЙ",
    price: 30,
    img: "peaGreen.webp",
  },
  {
    id: 25,
    title: "ГОРОХ ЖОВТИЙ",
    price: 40,
    img: "peaYellow.webp",
  },
  {
    id: 26,
    title: "КВАСОЛЯ ЧЕРВОНА",
    price: 46,
    img: "bean.webp",
  },
  {
    id: 27,
    title: "КВАСОЛЯ БІЛА",
    price: 50,
    img: "beanWhite.webp",
  },
  {
    id: 28,
    title: "НУТ",
    price: 60,
    img: "chickpeas.webp",
  },
  {
    id: 29,
    title: "БОБИ",
    price: 70,
    img: "beans.webp",
  },
  {
    id: 30,
    title: "ВІКА",
    price: 80,
    img: "vika.webp",
  },
  {
    id: 31,
    title: "СОЄВЕ БОРОШНО",
    price: 180,
    img: "soyFlour.webp",
  },
  {
    id: 32,
    title: "СОНЯШНИКОВИЙ ШРОТ",
    price: 30,
    img: "sunflowerMeal.webp",
  },
  {
    id: 33,
    title: "СОЄВИЙ ЖМИХ",
    price: 20,
    img: "soyCake.webp",
  },
  {
    id: 34,
    title: "СОНЯШНИКОВИЙ ЖМИХ",
    price: 20,
    img: "sunflowerCake.webp",
  },
  {
    id: 35,
    title: "ОБВАЛЕНА СОЧЕВИЦЯ",
    price: 150,
    img: "lentlisRolled.webp",
  },
  {
    id: 36,
    title: "ПШОНО",
    price: 180,
    img: "retailMillet.webp",
  },
  {
    id: 37,
    title: "ВІВСЯНІ ПЛАСТІВЦІ",
    price: 280,
    img: "oatFlakes.webp",
  },
  {
    id: 38,
    title: "КОЛОТИЙ ГОРОХ ЗЕЛЕНИЙ",
    price: 144,
    img: "PickedPeasGreen.webp",
  },
  {
    id: 39,
    title: "КОЛОТИЙ ГОРОХ ЖОВТИЙ",
    price: 144,
    img: "PickedPeasYellow.webp",
  },
];
